version: '3'
services:
  node:
    image: etrium/website
    container_name: etrium-website
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    networks:
      - etrium-network
networks:
  etrium-network:
    external: true
